#! /usr/bin/env bash


# Get the path to this script
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

# Create a symlink to update the current down script
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Load the current (turing) theme
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Start the compositor
if [ -x "$(command -v picom)" ]; then
   picom --config "${SCRIPTPATH}/confs/picom/picom.conf" &
fi

# Start eww
if [ -x "$(command -v eww)" ]; then
   eww open topbar --config "${SCRIPTPATH}/confs/eww" &
fi

# Start the notification daemon
if [ -x "$(command -v dunst)" ]; then
   dunst -config "${SCRIPTPATH}/confs/dunst/dunstrc" &
fi

# Restore the wallpapers and the colorscheme
wal -R
