#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom -b &
udiskie &
nitrogen --restore

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI 

bspc config border_width         1
bspc config window_gap          40
bspc config focused_border_color "#F8F4F9"
bspc config normal_border_color "#22223B"

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a thunar state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
