#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Start Picom if it exists
if [ -x "$(command -v picom)" ]; then
	picom --config $SCRIPTPATH/picom.conf &
fi

# Set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# Set the background
if [ -x "$(command -v nitrogen)" ]; then
	nitrogen --restore &
fi

# Start Polybar
if [ -x "$(command -v polybar)" ]; then
	polybar cygnusbar -c $SCRIPTPATH/polybar.config &
fi

# Start the notification daemon
if [ -x "$(command -v dunst)" ]; then
	pkill dunst
	dunst &
fi

